# -*- coding: utf-8 -*-
"""plot_mfccs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmh4bCE41ZQxi4sUA17vTe90dsFyBL53
"""

def plot_mfccs(mfcc_choice,t_choice):
  fig1, axs1 = plt.subplots(nrows=1,ncols=1,figsize=[10,5])
  X = np.linspace(0,np.shape(mfcc_choice)[0],5)
  Xlab = np.linspace(0,max(t_choice),5)
  c = axs1.pcolor(np.transpose(mfcc_choice))
  axs1.set_title('Completing the “Cepstrum"', weight='bold',fontsize=20,color='black')
  axs1.set_xticks(X)
  axs1.set_xticklabels(Xlab)
  plt.xticks(fontsize=15)
  plt.yticks(fontsize=15)
  axs1.set_ylabel('MFCC Coefficients',weight='bold',size=15)
  axs1.set_xlabel('Time\n(Seconds)',weight='bold',size=15)
  fig1.colorbar(c , ax = axs1)
  plt.tight_layout()