# -*- coding: utf-8 -*-
"""SNR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z_XULRuKcFcT0YIDUAOfwV3UqTLAQy-_
"""

# Adding noise using target SNR
def SNR(SNR,data):
  # Set a target SNR
  target_snr_db = SNR
  # Calculate signal power and convert to dB 
  sig_avg_watts = np.mean(data**2)
  sig_avg_db = 10 * np.log10(sig_avg_watts)
  # Calculate noise according to [2] then convert to watts
  noise_avg_db = sig_avg_db - target_snr_db
  noise_avg_watts = 10 ** (noise_avg_db / 10)
  # Generate an sample of white noise
  mean_noise = 0
  added_noise = np.random.normal(mean_noise, np.sqrt(noise_avg_watts), len(data**2))
  # Noise up the original signal
  data = data + added_noise
  return(data,added_noise)